package com.bookstore.entity;
// Generated Oct 8, 2021 10:15:00 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail")
@NamedQueries({
	@NamedQuery(name="OrderDetail.bestSelling", query="select od.book from OrderDetail od group by od.book.bookId order by sum(od.quantity) desc")
})
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id = new OrderDetailId();
	private Book book;
	private BookOrder bookOrder;
	
	private int quantity;
	private float subTotal;

	public OrderDetail() {
	}

//	public OrderDetail(OrderDetailId id) {
//		this.id = id;
//	}

//	public OrderDetail(OrderDetailId id, Book book, BookOrder bookOrder) {
//		this.id = id;
//		this.book = book;
//		this.bookOrder = bookOrder;
//	}
	
//	public OrderDetail(Book book, BookOrder bookOrder) {
//		this.id = new OrderDetailId(book, bookOrder);
//		this.book = book;
//		this.bookOrder = bookOrder;
//	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id")),
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id")) })
	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.id.setBook(book);
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", insertable = false, updatable = false)
	public BookOrder getBookOrder() {
		return this.bookOrder;
	}

	public void setBookOrder(BookOrder bookOrder) {
		this.id.setBookOrder(bookOrder);
		this.bookOrder = bookOrder;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	@Column(name = "sub_total")
	public float getSubTotal() {
		return subTotal;
	}

	public void setSubTotal(float subTotal) {
		this.subTotal = subTotal;
	}
	
	
}
